name = "AoC2020"
uuid = "beeedd1c-a677-48be-9e9a-843ef5ac7322"
authors = ["Theo Garefalakis <tgaref@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CombinedParsers = "5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
